'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.239
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("D2RIC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _40px_Aghanim_s_Scepter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Aghanim_s_Scepter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Animal_Courier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Animal_Courier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Arcane_Boots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Arcane_Boots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Armlet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Armlet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Assault_Cuirass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Assault_Cuirass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Battle_Fury() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Battle_Fury", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Belt_of_Strength() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Belt_of_Strength", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Black_King_Bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Black_King_Bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Blade_Mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Blade_Mail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Blade_of_Alacrity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Blade_of_Alacrity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Blades_of_Attack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Blades_of_Attack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Blink_Dagger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Blink_Dagger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Bloodstone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Bloodstone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Boots_of_Elvenskin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Boots_of_Elvenskin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Boots_of_Speed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Boots_of_Speed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Boots_of_Travel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Boots_of_Travel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Bottle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Bottle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Bracer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Bracer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Broadsword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Broadsword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Buckler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Buckler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Butterfly() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Butterfly", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Chainmail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Chainmail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Circlet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Circlet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Clarity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Clarity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Claymore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Claymore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Cloak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Cloak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Crystalys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Crystalys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Daedalus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Daedalus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Dagon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Dagon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Dagon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Dagon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Dagon3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Dagon3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Dagon4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Dagon4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Dagon5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Dagon5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Demon_Edge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Demon_Edge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Desolator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Desolator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Diffusal_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Diffusal_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Diffusal_Blade2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Diffusal_Blade2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Divine_Rapier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Divine_Rapier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Drum_of_Endurance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Drum_of_Endurance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Dust_of_Appearance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Dust_of_Appearance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Eaglesong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Eaglesong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Energy_Booster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Energy_Booster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ethereal_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ethereal_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Eul_s_Scepter_of_Divinity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Eul_s_Scepter_of_Divinity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Eye_of_Skadi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Eye_of_Skadi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Flying_Courier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Flying_Courier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Force_Staff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Force_Staff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Gauntlets_of_Strength() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Gauntlets_of_Strength", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Gem_of_True_Sight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Gem_of_True_Sight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ghost_Scepter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ghost_Scepter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Gloves_of_Haste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Gloves_of_Haste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Hand_of_Midas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Hand_of_Midas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Headdress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Headdress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Healing_Salve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Healing_Salve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Heart_of_Tarrasque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Heart_of_Tarrasque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Helm_of_Iron_Will() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Helm_of_Iron_Will", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Helm_of_the_Dominator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Helm_of_the_Dominator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Hood_of_Defiance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Hood_of_Defiance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Hyperstone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Hyperstone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Iron_Branch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Iron_Branch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Javelin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Javelin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Linken_s_Sphere() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Linken_s_Sphere", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Maelstrom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Maelstrom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Magic_Stick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Magic_Stick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Magic_Wand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Magic_Wand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Manta_Style() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Manta_Style", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Mantle_of_Intelligence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Mantle_of_Intelligence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Mask_of_Madness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Mask_of_Madness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Medallion_of_Courage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Medallion_of_Courage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Mekansm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Mekansm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Mithril_Hammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Mithril_Hammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Mjollnir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Mjollnir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Monkey_King_Bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Monkey_King_Bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Morbid_Mask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Morbid_Mask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Mystic_Staff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Mystic_Staff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Necronomicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Necronomicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Necronomicon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Necronomicon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Necronomicon3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Necronomicon3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Null_Talisman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Null_Talisman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Oblivion_Staff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Oblivion_Staff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Observer_Ward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Observer_Ward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ogre_Club() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ogre_Club", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Orb_of_Venom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Orb_of_Venom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Orchid_Malevolence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Orchid_Malevolence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Perseverance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Perseverance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Phase_Boots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Phase_Boots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Pipe_of_Insight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Pipe_of_Insight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Platemail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Platemail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Point_Booster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Point_Booster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Poor_Man_s_Shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Poor_Man_s_Shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Power_Treads() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Power_Treads", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Quarterstaff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Quarterstaff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Quelling_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Quelling_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Radiance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Radiance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Reaver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Reaver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Refresher_Orb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Refresher_Orb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ring_of_Basilius() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ring_of_Basilius", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ring_of_Health() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ring_of_Health", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ring_of_Protection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ring_of_Protection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ring_of_Regen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ring_of_Regen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Robe_of_the_Magi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Robe_of_the_Magi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Sacred_Relic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Sacred_Relic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Sage_s_Mask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Sage_s_Mask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Sange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Sange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Sange_and_Yasha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Sange_and_Yasha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Satanic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Satanic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Scythe_of_Vyse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Scythe_of_Vyse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Sentry_Ward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Sentry_Ward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Shadow_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Shadow_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Shiva_s_Guard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Shiva_s_Guard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Skull_Basher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Skull_Basher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Slippers_of_Agility() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Slippers_of_Agility", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Smoke_of_Deceit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Smoke_of_Deceit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Soul_Booster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Soul_Booster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Soul_Ring() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Soul_Ring", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Staff_of_Wizardry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Staff_of_Wizardry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Stout_Shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Stout_Shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Talisman_of_Evasion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Talisman_of_Evasion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Tango() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Tango", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Town_Portal_Scroll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Town_Portal_Scroll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Ultimate_Orb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Ultimate_Orb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Urn_of_Shadows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Urn_of_Shadows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Vanguard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Vanguard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Veil_of_Discord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Veil_of_Discord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Vitality_Booster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Vitality_Booster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Vladmir_s_Offering() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Vladmir_s_Offering", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Void_Stone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Void_Stone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Wraith_Band() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Wraith_Band", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _40px_Yasha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_40px_Yasha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property none() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("none", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
